# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [26]:
import numpy as np





### 2. Print the NUMPY version and the configuration.


In [52]:
print(np.version)
np.show_config


<module 'numpy.version' from 'c:\\Users\\vinyj\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>


<function numpy.__config__.show(mode='stdout')>

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [74]:
a = np.random.random((2,3,5))




### 4. Print a.


In [41]:
print(a)

[[[0.09866923 0.67301033 0.75463142 0.75519035 0.60508454]
  [0.01699005 0.79555709 0.87897717 0.26805644 0.50515154]
  [0.07428237 0.38834444 0.70596107 0.80485384 0.775291  ]]

 [[0.83481752 0.47852316 0.78846835 0.10819936 0.22781034]
  [0.34912528 0.40894611 0.58933665 0.07847043 0.37098217]
  [0.54984183 0.25718412 0.83481856 0.7812377  0.0143514 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [49]:
b = np.ones((5,2,3))


### 6. Print b.


In [57]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [58]:
print(a.shape == b.shape)

False



### 8. Are you able to add a and b? Why or why not?


In [84]:
print(a + b)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [80]:
c = np.transpose(b, (1,2,0))
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [82]:
d = a + c
print(d)


[[[1.56719701 1.29170239 1.5460146  1.26226557 1.37411398]
  [1.1577903  1.1683661  1.37274643 1.05799649 1.74292765]
  [1.75954457 1.64448732 1.67190466 1.65295955 1.06574421]]

 [[1.13414685 1.27370137 1.40473417 1.9678915  1.85519813]
  [1.92506278 1.41002531 1.68758813 1.32542136 1.26773802]
  [1.12187831 1.3638172  1.37176038 1.0034031  1.93518866]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [118]:
print("a:\n", a)
print("d:\n", d)



a:
 [[[0.56719701 0.29170239 0.5460146  0.26226557 0.37411398]
  [0.1577903  0.1683661  0.37274643 0.05799649 0.74292765]
  [0.75954457 0.64448732 0.67190466 0.65295955 0.06574421]]

 [[0.13414685 0.27370137 0.40473417 0.9678915  0.85519813]
  [0.92506278 0.41002531 0.68758813 0.32542136 0.26773802]
  [0.12187831 0.3638172  0.37176038 0.0034031  0.93518866]]]
d:
 [[[1.56719701 1.29170239 1.5460146  1.26226557 1.37411398]
  [1.1577903  1.1683661  1.37274643 1.05799649 1.74292765]
  [1.75954457 1.64448732 1.67190466 1.65295955 1.06574421]]

 [[1.13414685 1.27370137 1.40473417 1.9678915  1.85519813]
  [1.92506278 1.41002531 1.68758813 1.32542136 1.26773802]
  [1.12187831 1.3638172  1.37176038 1.0034031  1.93518866]]]



### 12. Multiply a and c. Assign the result to e.


In [90]:
e = a + c 
print(e)


[[[1.56719701 1.29170239 1.5460146  1.26226557 1.37411398]
  [1.1577903  1.1683661  1.37274643 1.05799649 1.74292765]
  [1.75954457 1.64448732 1.67190466 1.65295955 1.06574421]]

 [[1.13414685 1.27370137 1.40473417 1.9678915  1.85519813]
  [1.92506278 1.41002531 1.68758813 1.32542136 1.26773802]
  [1.12187831 1.3638172  1.37176038 1.0034031  1.93518866]]]




### 13. Does e equal to a? Why or why not?


In [91]:
print(e.shape == a.shape)

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [111]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)



1.9678915008303268 1.003403102271501 1.446110537439043



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [108]:
f = np.empty((2,3,5))
print(f)




[[[1.56719701 1.29170239 1.5460146  1.26226557 1.37411398]
  [1.1577903  1.1683661  1.37274643 1.05799649 1.74292765]
  [1.75954457 1.64448732 1.67190466 1.65295955 1.06574421]]

 [[1.13414685 1.27370137 1.40473417 1.9678915  1.85519813]
  [1.92506278 1.41002531 1.68758813 1.32542136 1.26773802]
  [1.12187831 1.3638172  1.37176038 1.0034031  1.93518866]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [112]:
# Garantir que f tenha a mesma forma de d
f = np.empty_like(d)

# Calcular os valores de referência
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Preencher f com base nas condições
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i, j, k]
            if val == d_min:
                f[i, j, k] = 0
            elif val > d_min and val < d_mean:
                f[i, j, k] = 25
            elif val == d_mean:
                f[i, j, k] = 50
            elif val > d_mean and val < d_max:
                f[i, j, k] = 75
            elif val == d_max:
                f[i, j, k] = 100







### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [117]:
print("d:\n", d)
print("f:\n", f)


d:
 [[[1.56719701 1.29170239 1.5460146  1.26226557 1.37411398]
  [1.1577903  1.1683661  1.37274643 1.05799649 1.74292765]
  [1.75954457 1.64448732 1.67190466 1.65295955 1.06574421]]

 [[1.13414685 1.27370137 1.40473417 1.9678915  1.85519813]
  [1.92506278 1.41002531 1.68758813 1.32542136 1.26773802]
  [1.12187831 1.3638172  1.37176038 1.0034031  1.93518866]]]
f:
 [[[ 75.  25.  75.  25.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  75.  75.  25.]]

 [[ 25.  25.  25. 100.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  25.  25.   0.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [121]:
g = np.empty((2, 3, 5), dtype=str)  # mesma forma, mas com strings

for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            val = f[i, j, k]
            if val == 0:
                g[i, j, k] = "A"
            elif val == 25:
                g[i, j, k] = "B"
            elif val == 50:
                g[i, j, k] = "C"
            elif val == 75:
                g[i, j, k] = "D"
            elif val == 100:
                g[i, j, k] = "E"

print(g)


[[['D' 'B' 'D' 'B' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'D' 'D' 'B']]

 [['B' 'B' 'B' 'E' 'D']
  ['D' 'B' 'D' 'B' 'B']
  ['B' 'B' 'B' 'A' 'D']]]
